const newQuestions = [
  {
    question: 'links roma',
    title: 'Manchester United 🆚 AS ROMA',
    time: '3:00 PM',
    place: 'Old Trafford',
    referi: 'Carlos del Cerro',
    link1: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link2: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link3: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link4: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link5: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
  },
  {
    question: 'links roma2',
    title: 'Manchester United 🆚 AS ROMA',
    time: '3:10 PM',
    place: 'Old Trafford2',
    referi: 'Carlos del Cerro2',
    link1: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link2: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link3: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link4: '',
    link5: '',
  },
  {
    question: 'links roma3',
    title: 'Manchester United 🆚 AS ROMA',
    time: '3:15 PM',
    place: 'Old Trafford2',
    referi: 'Carlos del Cerro3',
    link1: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link2: 'http://www.ovostreams.com/tottenham-vs-aston-villa.php',
    link3: '',
    link4: '',
    link5: '',
  },
  {
    question: '',
    title: ' 🆚 ',
    time: '',
    place: '',
    referi: '',
    link1: '',
    link2: '',
    link3: '',
    link4: '',
    link5: '',
  },
];

module.exports = { newQuestions };
